import { type } from 'os';

export type dataList = {
  ath: number;
  ath_change_percentage: number;
  ath_date: string;
  atl: number;
  atl_change_percentage: number;
  atl_date: string;
  circulating_supply: number;
  current_price: number;
  fully_diluted_valuation: number;
  high_24h: number;
  id: string;
  image: string;
  last_updated: string;
  low_24h: number;
  market_cap: number;
  market_cap_change_24h: number;
  market_cap_change_percentage_24h: number;
  market_cap_rank: number;
  max_supply: number;
  name: string;
  price_change_24h: number;
  price_change_percentage_24h: number;
  roi: undefined;
  symbol: string;
  total_supply: number;
  total_volume: number;
};

export type singleCoinType = {
  ath: number;
  ath_change_percentage: number;
  ath_date: string;
  atl: number;
  atl_change_percentage: number;
  atl_date: string;
  circulating_supply: number;
  current_price: number;
  fully_diluted_valuation: number;
  high_24h: number;
  id: string;
  last_updated: string;
  low_24h: number;
  market_cap: number;
  market_cap_change_24h: number;
  market_cap_change_percentage_24h: number;
  market_cap_rank: number;
  max_supply: number;
  name: string;
  price_change_24h: number;
  price_change_percentage_24h: number;
  roi: undefined;
  symbol: string;
  total_supply: number;
  total_volume: number;
  additional_notices: [];
  asset_platform_id: null;
  platforms: object;
  block_time_in_minutes: number;
  categories: string[];
  coingecko_rank: number;
  coingecko_score: number;
  community_data: object;
  community_score: 82.848;
  country_origin: '';
  description: {
    ar: string;
    bg: string;
    cs: string;
    da: string;
    de: string;
    el: string;
    en: string;
    es: string;
    fi: string;
    fr: string;
    he: string;
    hi: string;
    hr: string;
    hu: string;
    id: string;
    it: string;
    ja: string;
    ko: string;
    lt: string;
    nl: string;
    no: string;
    pl: string;
    pt: string;
    ro: string;
    ru: string;
    sk: string;
    sl: string;
    sv: string;
    th: string;
    tr: string;
    uk: string;
    vi: string;
    zh: string;
  };
  developer_data: object;
  developer_score: number;
  genesis_date: string;
  hashing_algorithm: string;
  image: { thumb: string; small: string; large: string };
  links: object;
  liquidity_score: number;
  localization: object;
  market_data: {
    ath: object;
    ath_change_percentage: object;
    ath_date: object;
    atl: object;
    atl_change_percentage: object;
    atl_date: object;
    circulating_supply: number;
    current_price: { [key: string]: number }; // CURRENT PRICE
    high_24h: { [key: string]: number };
    last_updated: string;
    low_24h: { [key: string]: number };
    market_cap: { [key: string]: number };
    market_cap_change_24h: number;
    market_cap_change_24h_in_currency: { [key: string]: number };
    market_cap_change_percentage_24h: number;
    market_cap_change_percentage_24h_in_currency: { [key: string]: number };
    market_cap_rank: number;
    max_supply: number;
    mcap_to_tvl_ratio: null;
    price_change_24h: number;
    price_change_24h_in_currency: { [key: string]: number };
    price_change_percentage_1h_in_currency: { [key: string]: number };
    price_change_percentage_1y: number;
    price_change_percentage_1y_in_currency: { [key: string]: number };
    price_change_percentage_7d: number;
    price_change_percentage_7d_in_currency: { [key: string]: number };
    price_change_percentage_14d: number;
    price_change_percentage_14d_in_currency: { [key: string]: number };
    price_change_percentage_24h: number;
    price_change_percentage_24h_in_currency: { [key: string]: number };
    price_change_percentage_30d: number;
    price_change_percentage_30d_in_currency: { [key: string]: number };
    price_change_percentage_60d: number;
    price_change_percentage_60d_in_currency: { [key: string]: number };
    price_change_percentage_200d: number;
    price_change_percentage_200d_in_currency: { [key: string]: number };
    roi: null;
    total_supply: number;
    total_value_locked: null;
    total_volume: { [key: string]: number };
  };
  public_interest_score: number;
  public_interest_stats: object;
  public_notice: null;
  sentiment_votes_down_percentage: number;
  sentiment_votes_up_percentage: number;
  status_updates: [];
  tickers: object;
};
